In [1]:
import numpy as np
import torch
import pandas as pd

## 1.1 Torch Tensors

### 1.1.1 Transferring from an array

In [2]:
arr = [[1, 2], [3, 4]]
print ("array: \n", arr, "\n")

arr1 = np.array(arr)
print("Numpy array: \n", arr1, "\n")

arr2 = torch.Tensor(arr)
print("Torch Tensor: ", arr2, "\n")

array: 
 [[1, 2], [3, 4]] 

Numpy array: 
 [[1 2]
 [3 4]] 

Torch Tensor:  
 1  2
 3  4
[torch.FloatTensor of size 2x2]
 



### 1.1.2 Matrices with default values

In [3]:
arr = np.ones((2,2))
print ("Numpy array: \n", arr, "\n")

arr1 = torch.ones((2,2))
print("Torch Tensor: ", arr1, "\n")

Numpy array: 
 [[1. 1.]
 [1. 1.]] 

Torch Tensor:  
 1  1
 1  1
[torch.FloatTensor of size 2x2]
 



In [4]:
arr = np.zeros((2,2))
print ("Numpy array: \n", arr, "\n")

arr1 = torch.zeros((2,2))
print("Torch Tensor: ", arr1, "\n")

Numpy array: 
 [[0. 0.]
 [0. 0.]] 

Torch Tensor:  
 0  0
 0  0
[torch.FloatTensor of size 2x2]
 



In [5]:
arr1 = torch.eye(3,3)
print("Torch Tensor: ", arr1, "\n")

arr1 = torch.eye(4,6)
print("Torch Tensor: ", arr1, "\n")

Torch Tensor:  
 1  0  0
 0  1  0
 0  0  1
[torch.FloatTensor of size 3x3]
 

Torch Tensor:  
 1  0  0  0  0  0
 0  1  0  0  0  0
 0  0  1  0  0  0
 0  0  0  1  0  0
[torch.FloatTensor of size 4x6]
 



※ `torch.numel()` return the number of components in the matrix.

In [6]:
a = torch.ones(1,2,3,4,5)
print(torch.numel(a))

a = torch.zeros(4,4)
print(torch.numel(a))

120
16


### 1.1.3 Matrices with random values (with seeds)

In [7]:
np.random.seed(0)
arr = np.random.rand(2,2)
print ("Numpy array: \n", arr, "\n")

torch.manual_seed(0)
arr1 = torch.rand(2, 2)
print("Torch Tensor: ", arr1, "\n")

Numpy array: 
 [[0.5488135  0.71518937]
 [0.60276338 0.54488318]] 

Torch Tensor:  
 0.4963  0.7682
 0.0885  0.1320
[torch.FloatTensor of size 2x2]
 



**Seeds when using GPUs**

In [8]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

### 1.1.4 One-dimensional tensor

In [9]:
torch.linspace(start=-10, end=10, steps=8) # divided into N steps


-10.0000
 -7.1429
 -4.2857
 -1.4286
  1.4286
  4.2857
  7.1429
 10.0000
[torch.FloatTensor of size 8]

In [10]:
torch.arange(3,15,2)  # Length of each steps = N


  3
  5
  7
  9
 11
 13
[torch.FloatTensor of size 6]

## 1.2 Bridge between Numpy and Torch 

### 1.2.1 Numpy to Torch 

In [11]:
np_arr = np.ones((2,2))*3
print ("Numpy array: \n", np_arr, "\nType: ", type(np_arr), "\n")

#Convert from np array
torch_tensor = torch.from_numpy(np_arr)   
print ("Torch Tensor: ", torch_tensor, "Type: ", type(torch_tensor), "\n")

Numpy array: 
 [[3. 3.]
 [3. 3.]] 
Type:  <class 'numpy.ndarray'> 

Torch Tensor:  
 3  3
 3  3
[torch.DoubleTensor of size 2x2]
 Type:  <class 'torch.DoubleTensor'> 



### Q: What's the difference between `torch.from_numpy(np_arr)` & `torch.tensor(np_arr)`?

** Caution: This conversion only support **`double`, `float`, `int64`, `int32`, and `uint8`

In [28]:
# intentional error
torch.from_numpy(np.ones((2,2),dtype=np.int8))

RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.

** Following table compares the data types before & after the conversion **

In [13]:
dtypes = [np.uint8, np.int32, np.int64, np.float32, np.float, np.float64, np.double, ]
npArr_dtypes = [((dtype).__name__) for dtype in dtypes]
tensor_list = [torch.from_numpy(np.ones((1),dtype=dtype)) for dtype in dtypes]
tensor_types = [(type(tensor).__name__) for tensor in tensor_list]
pd.concat([pd.DataFrame({'dtypes': npArr_dtypes}), \
           pd.DataFrame({'Tensor types': tensor_types})],axis=1).style

### 1.2.2 Torch to Numpy

In [14]:
torch_tensor = torch.ones(2,2)
np_arr = torch_tensor.numpy()
print(type(np_arr))

<class 'numpy.ndarray'>


## 1.3 Torch Tensors moving between CPU & GPU

In [15]:
tensor = torch.ones(2,2)

# move to GPU
if torch.cuda.is_available():
    tensor.cuda() 
    
# move back to CPU
tensor.cpu()


 1  1
 1  1
[torch.FloatTensor of size 2x2]

## 1.4 Tensor Operations

### 1.4.1 Resizing & Permute

In [16]:
arr = torch.arange(0,16)
print("Size of original array:\n", arr.size(), "\n")

Size of original array:
 torch.Size([16]) 



In [17]:
# view(): view the tensor in assigned shape 
print("arr.view(-1,2,4)) =", arr.view(-1,2,4)) # -1 means unknown numbers
print(arr.size())  # view() won't assign values to array

arr.view(-1,2,4)) = 
(0 ,.,.) = 
   0   1   2   3
   4   5   6   7

(1 ,.,.) = 
   8   9  10  11
  12  13  14  15
[torch.FloatTensor of size 2x2x4]

torch.Size([16])


In [18]:
arr = arr.view(-1,2,4)  # assign values to array
print(arr.size())

torch.Size([2, 2, 4])


In [19]:
arr = arr.permute(0,1,2) # same sequence of dimension, won't change the array
print(arr.size())
arr = arr.permute(0,2,1) # change the last two dimensions
print(arr.size())

torch.Size([2, 2, 4])
torch.Size([2, 4, 2])


### 1.4.2 add, sub, mul, & div
Only take addition as example here, other 3 operations are used in the same way.

In [20]:
a, b= torch.ones(2,2), torch.ones(2,2)*2
print("a =",a,"\nb =",b)

a = 
 1  1
 1  1
[torch.FloatTensor of size 2x2]
 
b = 
 2  2
 2  2
[torch.FloatTensor of size 2x2]



In [21]:
# Element-wise operation
print("torch.add(a,b) =", torch.add(a,b))  #same as (a + b)

torch.add(a,b) = 
 3  3
 3  3
[torch.FloatTensor of size 2x2]



**The difference between **`add()`** & **`add_()`** is explained here. Subtraction, multiplication, & division also have same characteristic.**

In [22]:
# In-place operation (without assigning values)
c = a.add(b)
print(c)
print(a) # a remained the same


 3  3
 3  3
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [23]:
# In-place operation (with assigning values)
c = a.add_(b)
print(c)
print(a) # a changed


 3  3
 3  3
[torch.FloatTensor of size 2x2]


 3  3
 3  3
[torch.FloatTensor of size 2x2]



### 1.4.3 Mean & Standard Deviation

In [24]:
a = torch.arange(3,9).view(3,-1)
print(a)


 3  4
 5  6
 7  8
[torch.FloatTensor of size 3x2]



In [25]:
a.mean(dim=0) #mean along axis 0


 5
 6
[torch.FloatTensor of size 2]

In [26]:
a.mean(dim=1) #mean along axis 1


 3.5000
 5.5000
 7.5000
[torch.FloatTensor of size 3]

In [27]:
torch.arange(0,17).std(dim=0)


 5.0498
[torch.FloatTensor of size 1]